project2.out: project2.o fraction.o dictionary.o stack.h
	g++ -g -o project2.out project2.o fraction.o dictionary.o

fraction.o: fraction.cpp fraction.h
	g++ -c fraction.cpp

dictionary.o: dictionary.cpp dictionary.h
	g++ -c dictionary.cpp
